name: Build wheels (subdir)
on:
    push:
        paths:
        - 'rust/**'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./rust/kdragrs/.github/workflows/CI.yml
